/**
 * RX-S601 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.wa2c.android.medoly.plugin.action.avcontrol.source.network.data


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param responseCode
 * @param modelName
 * @param destination
 * @param deviceId
 * @param systemId
 * @param systemVersion
 * @param apiVersion
 * @param netmoduleGeneration
 * @param netmoduleVersion
 * @param netmoduleChecksum
 * @param operationMode
 * @param updateErrorCode
 */
@Serializable
data class GetDeviceInfoRes(
    @SerialName(value = "response_code") val responseCode: kotlin.Int? = null,
    @SerialName(value = "model_name") val modelName: kotlin.String? = null,
    @SerialName(value = "destination") val destination: kotlin.String? = null,
    @SerialName(value = "device_id") val deviceId: kotlin.String? = null,
    @SerialName(value = "system_id") val systemId: kotlin.String? = null,
    @SerialName(value = "system_version") val systemVersion: kotlin.Double? = null,
    @SerialName(value = "api_version") val apiVersion: kotlin.Double? = null,
    @SerialName(value = "netmodule_generation") val netmoduleGeneration: kotlin.Int? = null,
    @SerialName(value = "netmodule_version") val netmoduleVersion: kotlin.String? = null,
    @SerialName(value = "netmodule_checksum") val netmoduleChecksum: kotlin.String? = null,
    @SerialName(value = "operation_mode") val operationMode: kotlin.String? = null,
    @SerialName(value = "update_error_code") val updateErrorCode: kotlin.String? = null
)

